### ISSUE TITLE
Jenkins Add-In is not compatible with Keptn 0.8

### ISSUE THREAD

**Issue by sergiohinojosa** [keptn-sandbox/keptn-in-a-box#11]
Keen an eye on 
https://github.com/keptn-sandbox/keptn-jenkins-library

pcjeff just uploaded a new library, test it and check if the quality gates pipelines with Jenkins work.

**Comment by sergiohinojosa** [comment]
Fixed by @pjeff. 1 and 2 work, somehow 3 is not pushing the events to Dynatrace and swallowing the JMeter file. Jmeter service is not triggered. Most probably has to do with the shipyard file.

**Comment by pcjeffmac** [comment]
I have run a series of test with the following, using the https://github.com/keptn-sandbox/keptn-jenkins-library

```groovy
@Library('keptn-library@4.0')_
import sh.keptn.Keptn
def keptn = new sh.keptn.Keptn()
```

I make sure to first download a shipyard file,
```groovy
keptn.downloadFile('<yourRpoGoesHere>/shipyard-performance.yaml', 'keptn/shipyard.yaml')
```

I then make sure to initialize with the shipyard file.
```groovy
// Initialize the Keptn Project
keptn.keptnInit project:"${params.Project}", service:"${params.Service}", stage:"${params.Stage}", monitoring:"${monitoring}", shipyard:'keptn/shipyard.yaml'
```

Finally, as documented, make sure to use the keptn.sendConfigurationTriggeredEvent for use with Keptn 8.x
```groovy
// send deployment finished to trigger tests
def keptnContext = keptn.sendConfigurationTriggeredEvent testStrategy:"${params.TestStrategy}", deploymentURI:"${params.DeploymentURI}" 
String keptn_bridge = env.KEPTN_BRIDGE
echo "Open Keptns Bridge: ${keptn_bridge}/trace/${keptnContext}"
```
Here is the shipyard file I use for my Performance test that does instantiate the jmeter service.

```yaml
apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "shipyard-performance"
spec:
  stages:
    - name: "performancestage"
      sequences:
        - name: "delivery"
          tasks:
            - name: "test"
              properties:
                teststrategy: "performance"
            - name: "evaluation"
```

Result in Jenkins,
![Screen Shot 2021-04-13 at 6 47 01 PM](https://user-images.githubusercontent.com/19553291/114630471-ad2fac00-9c88-11eb-9622-9fe094953a84.png)

Result in Keptn
![Screen Shot 2021-04-13 at 6 46 09 PM](https://user-images.githubusercontent.com/19553291/114630500-bb7dc800-9c88-11eb-9776-e3d55c8a07c3.png)

Next steps,
Clean deployment in AWS and another round of testing.
